### ISSUE TITLE
Maybe just maybe do some funky shit with the server so we can prank each other.

### ISSUE THREAD

**Issue by Komorebiao** [notoriouslogank/harbinger#20]
Example !makefight @playername causes a random mob to spawn in font of the player. This should probably be on cool down somehow but maybe don't go this route at all. Go do some other form of wacky command or integration. Either way being able to type in the discord chat and have something happen on the server would be cool.

**Comment by notoriouslogank** [comment]
@Komorebiao Ultimately that's one of the stretch goals.  Right now I'm trying to wrap my head around this combination of tmux/fabric/paper-minecraft I'm running; I *think* it can be done, but it's weird to try to send commands to the server because the server's already *running* at that point, so I'll have to attach to it.  I think tmux can cover that for me, though.

**Comment by notoriouslogank** [comment]
Done. #56
